### PR TITLE
KP-360: search function for programme syllabuses page

### PR DESCRIPTION
**Pull request by axelbjo**
- Added text input field and search function to let user filter programme syllabuses
- Updated SearchInput to with properties realTimeUpdates and label in order to make it a more general component that can be used in other places
- Added test cases for search

### CODE REVIEW

**Review by allazis — APPROVED** [review]
LGTM! 

Possibly add an info text for when there are no matches. Do so if you agree. Other than that it's perfect! Good job :)

**Review by amirhossein-haerian — APPROVED** [review]
LGTM,
The input component has been updated with a really neat approach 🙌
I also tested locally and it looks great, Good Job ⭐️

**Comment by axelbjo** [comment]
> LGTM!
> 
> Possibly add an info text for when there are no matches. Do so if you agree. Other than that it's perfect! Good job :)

Good idea!

**Review by karlandindrakryggen — APPROVED** [review]
Great job! 

I agree with Lotta about a text for when there is no matches would be good!

**Pull request merged**
